#!/bin/bash
set -e

AGENTSTRATOR_INSTALL_DIR="${AGENTSTRATOR_INSTALL_DIR:-$HOME/.agentstrator}"
VOLUME="$AGENTSTRATOR_INSTALL_DIR/volume"

if [ -f "$AGENTSTRATOR_INSTALL_DIR/commons.sh" ]; then
    source "$AGENTSTRATOR_INSTALL_DIR/commons.sh"
fi

docker run --rm -it \
    -v "$VOLUME:/agentstrator" \
    -u $(id -u):$(id -g) \
    -e HOME=/agentstrator \
    -e OPENCODE_CONFIG=/agentstrator/.config/opencode/opencode.json \
    -e OPENCODE_CONFIG_DIR=/agentstrator/.config/opencode \
    --entrypoint bash agentstrator-gentle-ai -c "
        export HOME=/agentstrator
        export OPENCODE_CONFIG=/agentstrator/.config/opencode/opencode.json
        export OPENCODE_CONFIG_DIR=/agentstrator/.config/opencode
        /usr/local/bin/gentle-ai uninstall --all
    "

rm -rf "$VOLUME/.config/gentle-ai" 2>/dev/null || true
rm -f "$VOLUME/.config/opencode/plugins/engram.ts" 2>/dev/null || true

echo "gentle-ai uninstalled successfully. Agent config files generated by gentle-ai sync were preserved in the volume."